const testdata = {
  status: '200',
  message: '상세 정보 가져오기에 성공하였습니다.',
  data: {
    curation_seq: '21403212',
    title: '오늘은 여기!',
    transportation: ['bus', 'car', 'walk'],
    budget: '130000',
    personal: '',
    fixed_people: '5',
    desc: '돈 걱정없이 맛있게 먹는 코스!',
    date: '',
    good: '137',
    views: '15032',
    member_seq: 'user_13823',
    member_nickname: 'TestNickName',
    photo_count: 5,
    curation_count: 3,
    curation_stores: [
      {
        address_name: '서울 영등포구 여의도동 85',
        category_group_code: '',
        category_group_name: '',
        category_name: '여행 > 공원 > 도시근린공원',
        distance: '',
        id: '10952963',
        phone: '02-3780-0561',
        place_name: '여의도한강공원',
        place_url: 'http://place.map.kakao.com/10952963',
        road_address_name: '',
        x: '126.93512931714196',
        y: '37.52638860108943',
      },
      {
        address_name: '서울 영등포구 여의도동 23-1',
        category_group_code: 'CT1',
        category_group_name: '문화시설',
        category_name: '문화,예술 > 영화,영상 > 영화관 > CJCGV',
        distance: '',
        id: '18133518',
        phone: '1544-1122',
        place_name: 'CGV 여의도',
        place_url: 'http://place.map.kakao.com/18133518',
        road_address_name: '서울 영등포구 국제금융로 10',
        x: '126.92558415024183',
        y: '37.52569010202313',
      },
      {
        address_name: '서울 영등포구 여의도동 23-1',
        category_group_code: '',
        category_group_name: '',
        category_name: '가정,생활 > 복합쇼핑몰',
        distance: '',
        id: '18203409',
        phone: '02-6137-5000',
        place_name: 'IFC몰',
        place_url: 'http://place.map.kakao.com/18203409',
        road_address_name: '서울 영등포구 국제금융로 10',
        x: '126.925955827282',
        y: '37.5250668422081',
      },
    ],
    comments: [
      {
        user_nickname: '천사유저',
        user_emogi: '',
        content: '너무 잘다녀왔어요!! 최고!!',
      },
      {
        user_nickname: '악플러_1',
        user_emogi: '',
        content: '정~~~말 맛없는걸요',
      },
      {
        user_nickname: '악플러_2',
        user_emogi: '',
        content: '이런데 왜감? 차라리 집에서 방콕할듯 쿠쿠루삥뽕',
      },
    ],
    curation_images: [
      {
        image_path: '',
        image_order: '',
        name: '',
      },
      {
        image_path: '',
        image_order: '',
        name: '',
      },
    ],
  },
};
export default testdata;
