const tags = {
  transportation: [
    { walk: '도보' },
    { bus: '버스' },
    { subway: '지하철' },
    { car: '자동차' },
    { taxi: '택시' },
    { bicycle: '자전거' },
  ],
  local: [
    { Jongno: '종로구' },
    { Jung: '중구' },
    { Yongsan: '용산구' },
    { Seongdong: '성동구' },
    { Gwangjin: '광진구' },
    { Dongdaemun: '동대문구' },
    { Jungnang: '중랑구' },
    { Seongbuk: '성북구' },
    { Gangbuk: '강북구' },
    { Dobong: '도봉구' },
    { Nowon: '노원구' },
    { Eunpyeong: '은평구' },
    { Seodaemun: '서대문구' },
    { Mapo: '마포구' },
    { Yangcheon: '양천구' },
    { Gangseo: '강서구' },
    { Guro: '구로구' },
    { Geumcheon: '금천구' },
    { Yeongdeungpo: '영등포구' },
    { Dongjak: '동작구' },
    { Gwanak: '관악구' },
    { Seocho: '서초구' },
    { Gangnam: '강남구' },
    { Songpa: '송파구' },
    { Gangdong: '강동구' },
  ],
  theme: [
    { date: '데이트' },
    { alone: '혼자' },
    { instar: '인스타감성' },
    { hokangs: '호캉스' },
    { alchol: '술' },
    { pet: '애견동반' },
    { study: '공부' },
    { drive: '드라이브' },
    { active: '활동적인' },
    { food: '식도락' },
    { healing: '힐링' },
    { museum: '전시회/미술관' },
  ],
};
export default tags;
